### ISSUE TITLE
Returns on each row do not sum up to total

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/PolicyBrain#214]
http://www.ospc.org/taxbrain/2231/

The first and second column results (returns & AGI) do not sum up to their totals. It seems like for all the tables by expended income bins, we're missing the negative expanded income row. Under current law, we have about 4.9 billion returns in the lower than zero bin.

The count column in this table can be used as a reference:
<img width="693" alt="screen shot 2016-03-28 at 2 57 58 pm" src="https://cloud.githubusercontent.com/assets/10549597/14086898/6fdce4de-f4f5-11e5-9052-a7a4ea4162b1.png">

**Comment by talumbau** [comment]
@Amy-Xu, dropping the negative expanded income is intentional, but I see that is is confusing that the sum of what is displayed doesn't add up to the total at the bottom. I see two possibilities for a fix:

 1. put a row for negative expanded income

 2. do the summing on what is displayed so the totals match up

do you have an idea on which is the correct one to do? option 2 is much easier for me, so I'm hoping option 2 is good. cc @MattHJensen

**Comment by Amy-Xu** [comment]
@talumbau Could you remind me why we intentionally dropped the negatives? I want to talk to the researcher who found this issue and see how necessary it is to add the negatives row. Will get back to you soon.

**Comment by talumbau** [comment]
hmm.. @MattHJensen would probably have the best answer. My recollection is that when we first did the grouping by income bins, we defined all the bin end points. We defined 0 as the minimum for the lowest bin. This left some records without a bin, so there was a decision to drop them. I don't know of a deeper explanation than that.

**Comment by Amy-Xu** [comment]
Matt said we should follow how other institutions deal with this issue. [An example](http://www.taxpolicycenter.org/model-estimates/number-tax-units-who-itemize-under-current-law-and-without-selected-itemized) I found here seems to say what we're doing currently is totally acceptable, but we just need a note like (2) in that example so users won't be confused why all rows do not sum up to the totals. cc @MattHJensen 

Is it difficult to add notes like that? @talumbau

**Comment by talumbau** [comment]
It wouldn't be too difficult to add as long as it was just some kind of "static" note that appeared at the bottom of the page. So, something in this area:

<img width="1185" alt="screen shot 2016-04-13 at 2 11 27 pm" src="https://cloud.githubusercontent.com/assets/1891418/14506099/c89b7cdc-0181-11e6-82d4-af2f23fb4200.png">

that went underneath the Source link. If that is a good place for the note on the results page and you have some agreed upon text to add, let me know and I can add it. If the note text would be more intricately placed on the results page (some kind of hover over or dynamically appearing based on certain tables) I will still take the text but will need to work with @mistakevin to get it on the page.

**Comment by talumbau** [comment]
@Amy-Xu if this issue is still relevant, can you create the note and add to an existing flatblock (or have @MattHJensen do that part), or close if this issue is no longer relevant?

**Comment by Amy-Xu** [comment]
Not quite sure whether we still need this note. I don't think we have it yet: the note saying total number of returns does not match the sum of all cells. Do we still need it?@MattHJensen

**Comment by MattHJensen** [comment]
I believe that some additional documentation here would be valuable, in line w Amy's suggestion. Leaving this open.

**Comment by hdoupe** [comment]
@Amy-Xu do you have a note in mind that we could use?

What do you think about saying: "The totals include the negative expanded income bin which is not shown in the table."

**Comment by Amy-Xu** [comment]
Depending on the row label. If the label is 0-10k (or something like that), that sounds good. If the row label says 'less than 10k', then probably modify the last part to 'which is excluded from the lowest income bin'. Your judgement call.

**Comment by martinholmer** [comment]
I have no idea what TaxBrain is doing with the Tax-Calculator distribution/difference table results for bins (rather than deciles), but Tax-Calculator is returning **all** the expanded income bins as can be seen from this definition of the bins:
```
WEBAPP_INCOME_BINS = [-9e99, 0, 9999, 19999, 29999, 39999, 49999, 74999, 99999,
                      199999, 499999, 1000000, 9e99]

WEBBIN_ROW_NAMES = ['<$10K', '$10-20K', '$20-30K', '$30-40K',
                    '$40-50K', '$50-75K', '$75-100K',
                    '$100-200K', '$200-500K',
                    '$500-1000K', '>$1000K', 'all']
```
If the bin row amounts don't add up to the totals on TaxBrain, it may be that the first `<10K` bin results are not being shown on TaxBrain.

**Comment by martinholmer** [comment]
TaxBrain Issue #214 has been resolved by [Tax-Calculator pull request 1889](https://github.com/open-source-economics/Tax-Calculator/pull/1889).

In order to use the corrected row label (which, following [Amy's suggestion](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/214#issuecomment-362079981), is now `$0-10K` rather than `<$10K`) TaxBrain code will have to be changed so that the WEBBIN_ROW_NAMES list is imported from `taxcalc.tbi` (rather than from `taxcalc.utils`).

@Amy-Xu @hdoupe
