### ISSUE TITLE
Adding UBI Functionality

### ISSUE THREAD

**Issue by andersonfrailey** [OpenSourcePolicyCenter/PolicyBrain#614]
I'm working on ways to add UBI functionality using the CPS file with TaxBrain and I'm hoping to get some feedback from those with a better grasp on the inner workings of the web-app on the feasibility of one idea I have. The general goal it to make it as easy as possible for a user to work their way to a budget neutral UBI.

The first step is adding a button on the results page, `Link to UBI Simulation`. It would be just like the `Link to Dynamic Simulations` button currently there. This would link to a page with two sections:

**Section A**: A table with a column for each year and four rows:
1. Total Revenue Change
2. Benefit Payment Projections
3. UBI Payments
4. Net.

Row one would be the same as the combined liability change row on the results page.
Row two would be the sum of extrapolated benefits that @hdoupe and @Amy-Xu are working on.
Row three would be total UBI payments made. When a user first goes to the page, this will be all zeros.
Row four would be the first two rows minus the third.

**Section B**: where the user specifies UBI level and taxability. This would have input boxes for the user to specify UBI amounts for the three categories we have, what percent of that is taxable, and whether or not it is adjusted for inflation.

[Here](https://docs.google.com/spreadsheets/d/1On04m0VqCGD-BzqfckLsvbBRS3wQH9k5vsXCgWKc90M/edit?usp=sharing) is a spreadsheet that lays it out.

When the user hit the calculate button, a calculator with the reform they specified on TaxBrain plus their UBI provisions is run and the results update section A.

This is a pretty rough idea, and again I'm not familiar enough with the web-app to have a good grasp on exactly how much complexity this would entail, so I'd love some feedback from those who know it all better.

**Comment by MattHJensen** [comment]
I am not sure which approach is better, but let me describe what I have had in mind previously: 

Include UBI and benefits relevant parameters in the standard TaxBrain input page. All of the relevant parameters will be in current_law_policy.json, so we can still programmatically generate the TaxBrain input page using our existing mechanism. 

1. We would need to add a new capability for graying out parameters that are only relevant to puf.csv vs. cps.csv, but that should be easier after I add a `compatible_data` field to current_law_policy.json (https://github.com/open-source-economics/Tax-Calculator/issues/1480). 

2. We would need to augment the standard TaxBrain static output pages with the total benefit amount, total UBI amount, net of benefits, ubi, and tax, and perhaps some other relevant parameters. 

3. We would need to incorporate the C-TAM imputed MTRs from the tax-calculator `behavior` class (adding them to tax MTRs), so that we can still run a partial equilibrium simulation and macro elasticity simulation. 

4. We would need to make sure that all of this works with OG-USA. 

Note that we could add 3 and 4 incrementally _if_ we implement a pleasant way to gray out some or all dynamic models when the user modifies the benefits or UBI parameters. 

Looking forward to comments on the feasibility and attractiveness of these two approaches!

**Comment by andersonfrailey** [comment]
@MattHJensen I see a few advantages of your idea. First, if it's all on the standard input page we don't have to worry about users not realizing they would need to go to another page to take advantage of the UBI functionality. Second, I would imagine it would take less time to deploy than developing an entirely new page on TaxBrain.

>We would need to incorporate the C-TAM imputed MTRs from the tax-calculator behavior class (adding them to tax MTRs), so that we can still run a partial equilibrium simulation and macro elasticity simulation

Are you thinking of adding including these in the TaxCalc package as a separate file like we do with the weights file? Or as part of the CPS dataset?

**Comment by MattHJensen** [comment]
> Are you thinking of adding including these in the TaxCalc package as a separate file like we do with the weights file? Or as part of the CPS dataset?

One of those, probably. I'm not sure which would be preferable.

**Comment by Amy-Xu** [comment]
Here're my two cents:

1. Since UBI doesn't work with expanded PUF data, step 1 from Matt's proposal:

>We would need to add a new capability for graying out parameters that are only relevant to puf.csv vs. cps.csv, but that should be easier after I add a compatible_data field to current_law_policy.json (open-source-economics/Tax-Calculator#1480).

seems to me is essential no matter which approach we're going to adopt.

2. UBI input fields, no matter in a standalone page or combined with current input, would be similar to what Anderson described. In other words, currently we do not guarantee budget neutral for any user-specified UBI reform.

3. It seems there will be less work if we put MTRs with cps.csv file, because no need to build new functions to read in separate file.

**Comment by MattHJensen** [comment]
Thanks @Amy-Xu. That all makes sense to me.

**Comment by hdoupe** [comment]
#614 is resolved. Closing
