### ISSUE TITLE
Better run number references for TB, dynamic and ccc

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/PolicyBrain#681]
I am in the middle of a project that tries to analyze requests submitted by our ccc/TaxBrain/dynamic users, and realized that we might need a better naming convention for run number reference. 

Currently, run requests are recorded in the following way:
```
TaxBrain: Starting at 1, in an increment of 1
Macro Elasticity: Starting at 1, in an increment of 1
Behavioral: Starting at 1, in an increment of 1
CCC: Starting at 1, in an increment of 1
```
On back-end database, by looking at the run reference alone, it's hard to tell whether this run belongs to macro, behavioral, or potentially CCC (since currently CCC is not being logged). It can be confusing to users as well.

For the purpose of clearer reference for both developers and users, better naming conventions are desired. New naming convention should, at least, not only uniquely record each request, but also be able to clearly identify the property (TB/Macro Elasticity/Behavioral/CCC) of each request. 

For example, we can use a concatenation of letter and number to record each run: 
```
TaxBrain: letter T followed by run number
Macro Elasticity: letter E followed by run number 
Behavioral: letter B followed by run number 
CCC: letter C followed by run number 
```
In this way, we won't mess up our current way of counting, and will hopefully make those reference number more informative. 

@martinholmer @MattHJensen @hdoupe 
Any comments, concerns or remarks are appreciated.

**Comment by talumbau** [comment]
This is an interesting idea, but I don't understand what the current numbering scheme is not providing that you need. For example, you mention:

> On back-end database, by looking at the run reference alone, it's hard to tell whether this run belongs to macro, behavioral, or potentially CCC (since currently CCC is not being logged). It can be confusing to users as well.

Are you saying that, due to the current numbering scheme, if you have a number like `2653` you don't know whether this is a TaxBrain run, or a macro run, or something else? If that is what you are saying, I agree that this is true. You would not know what `2653` refers to unless you were provided with the full URL of the result. However, I don't understand in what context you just have something like `2653` and then you have to figure out which type of run is referred to with this number.

In terms of the "back-end database", the idiomatic way to think of this is with Django models. In Django, we refer to model "instances", which are rows of a database. Again, it is true that if someone said, "I am interested in row with primary key 2653 in the database", that would not be sufficient to understand what they are talking about, because the *table* in the database was not specified. Specifying the table would be equivalent to figuring out which model type they are referring to, which would be sufficient to determine what type of run is being referred to.

To me, I think it would make sense to get more information on the problem you are trying to solve before committing to making this change. Currently, someone can uniquely identify a simulation from ospc.org with a full URL. Or, if they have access to the full database of simulations, they can refer to an instance of one of the "OutputURL" models, such as `DynamicElasticityOutputUrl(pk=1048)`, which again uniquely identifies a particular run.

I don't see how creating URLs of the form `www.ospc.org/taxbrain/t3456` would help.

**Comment by hdoupe** [comment]
I agree with @talumbau. If I remember correctly, you were digging through the log files. Would it make more sense to use more descriptive logging?
