### ISSUE TITLE
1.1.0 Release

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#700]
We are planning to do another PolicyBrain release in the next 2 to 3 weeks (around October 27).  This is part of a larger goal to release more often.  This allows us to add changes to PolicyBrain in smaller increments and work towards a smoother release process. 
 
The three goals for this next release are:
1. Put OG-USA back on TaxBrain ( #539 )
2. Front-end clean-up ( @GoFroggyRun would you mind listing the issues that you would like to resolve by the next release)
3. Increase test coverage and quality ( #699 )
 
If anyone would like to add another feature in this release, then we can discuss this in the comments section below.  We want to bite off a manageable chunk of work so that we can get the release off on schedule.  However, I am completely open to discussing the addition of new features or changes to this release.
 
Does anybody have an idea for what the the tag should be for the next release?  Does re-instating a feature constitute a "minor change" as defined at [semver.org](http://semver.org/)?

**Comment by martinholmer** [comment]
@hdoupe said:
> We are planning to do another PolicyBrain release in the next 2 to 3 weeks (around October 27).

What version of Tax-Calculator will the next PolicyBrain release use?
Will it use 0.11.0 or 0.12.0 (which could be make available soon)?

**Comment by martinholmer** [comment]
@hdoupe asked:
> Does anybody have an idea for what the the tag should be for the next release? Does re-instating a feature constitute a "minor change" as defined at [semver.org](http://semver.org)?

Because PolicyBrain doesn't really have a public API that is used by client projects, it is not obvious how to apply the principles of semantic versioning.  There are two logical alternatives:

1. If you view the public users of TaxBrain and CCC as "client projects", then any substantive change in the capabilities of TaxBrain or CCC would be a "major" change.

2. If you don't want to be that expansive about what constitutes a "major" change, then you could say any substantive change in TaxBrain or CCC capabilities would be a "minor" change.  Certainly calling a substantive change in capabilities a "bug fix" makes no sense.

So, version 1.0.3 does not offer the OG-USA capability and does not offer distribution and difference tables that use AGI bins, but the next version will offer both of these capabilities.  

So, using the **first perspective**, the next version would be 2.0.  In this approach, dropping the third "bug fix" number probably makes sense.  In this case, if the next version after the next does not add any new capabilities (but fixed bugs), it would be numbered 2.1.  Or, if it did offer new capabilities, it would be 3.0. 

On the other hand, using the **second perspective**, the next version would be 1.1.0.  In this case, if the next version after the next does not add any new capabilities (but fixed bugs), it would be numbered 1.1.1  Or, if it did offer new capabilities, it would be 1.2.0. 

To me, the second perspective seems the most sensible way to apply semantic versioning to PolicyBrain.

So, if others agree, the next release would be PolicyBrain version 1.1.0.

**Comment by hdoupe** [comment]
@martinholmer asked

> What version of Tax-Calculator will the next PolicyBrain release use?
Will it use 0.11.0 or 0.12.0 (which could be make available soon)?

I think PB will remain on Tax-Calculator 0.10.2 for this release.  0.11.0 requires some minor changes in the TaxBrain/Tax-Calculator interaction.  If there's time, I may tackle this, but I don't think there will be time.  In the following PB releases, the CPS will be added and that will require a TC version change to 0.12.0+.  So, I plan to wait until then to change the version.  Does this sound sensible to you?

**Comment by hdoupe** [comment]
@martinholmer I think I like the second perspective more.  I think using the first perspective would send us pretty high in the version count in the next year or two.  However, this isn't too uncommon with web applications (the Firefox version that I'm using is numbed 56.0).  

I'm not sure what would constitute a major change in the second perspective.  Would that involve removing/adding an app?

Defining a public API is something that we should start thinking about.  I'm not really sure how to define our public API right now.  TC's pubic API is pretty intuitive since users directly call its methods.  PB's public API is harder to define since it is really only called by the web.  The only other interactions that it has with applications outside of the web are the OSPC python libraries like Tax-Calculator.  At some point, a separate issue needs to be opened to discuss this further.

**Comment by GoFroggyRun** [comment]
@hdoupe asked:
>would you mind listing the issues that you would like to resolve by the next release

Sure. Here's a (tentative) list:

* Issue #673 and #683 (done via PR #684 )

* Issue #629 (done via PR #675 )

* Issue #678 (done via PR #694 )

* Issue #500 

* Issue #613 (shaky)

* Issue #616 and #617 (shaky, I might remove those options for the moment if can't have a complete fix)

**Comment by hdoupe** [comment]
Thanks @GoFroggyRun. I'll start a milestone for this release.

**Comment by martinholmer** [comment]
@hdoupe and @GoFroggyRun,

I'd like to add another (very simple) item for the PolicyBrain 1.1.0 release.

TaxBrain can add a preset for the Brown-Khanna GAIN Act that calls for an EITC expansion.

@MattHJensen requested this in [Tax-Calculator issue 1552](https://github.com/open-source-economics/Tax-Calculator/issues/1552).  The JSON reform file for that reform is now available at `taxcalc/reforms/BrownKhanna.json`.

All that is left to do is for TaxBrain to add it to the bottom of the `Presets` list in the `Get Started` section.

![screen shot 2017-10-12 at 11 20 13 am](https://user-images.githubusercontent.com/12170745/31521781-cebd9c3e-af78-11e7-9f49-19e6beec48bd.png)

**Comment by hdoupe** [comment]
PR's #722 and #724 are on the test app. I plan to push 1.1.0 to production at 4 PM today if nobody has any objections.

@MattHJensen @GoFroggyRun

**Comment by MattHJensen** [comment]
> I plan to push 1.1.0 to production at 4 PM today if nobody has any objections. 

Will this cause downtime?

**Comment by hdoupe** [comment]
Ah, good point.  The downtime shouldn't be too bad.  The front-end update would take about 5 minutes.  The node updates would just decrease computing power for half an hour or so.  I would do 3 or 4 nodes at a time.  So several nodes would be up throughout the update.

However, today is not a good day for downtime.  Further, if it takes longer than expected then that would not be good.  I'll do the update tonight around 9 or 10 PM.  Hopefully, we will be safe then.

**Comment by GoFroggyRun** [comment]
@hdoupe said: 
>I'll do the update tonight around 9 or 10 PM.

Sounds reasonable to me.

**Comment by hdoupe** [comment]
Release 1.1.0 is complete. Closing
