### ISSUE TITLE
Add GUI-generated JSON reform file to static output page

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#859]
The static TaxBrain output page should contain the GUI-generated JSON reform file that was sent to Tax-Calculator to generate the results now shown on that page.  This should be very easy to do in TaxBrain and would provide TaxBrain users with a number of benefits.  One benefit would be easier debugging.  Another benefit would be that users who are executing multiple runs that differ only slightly in their tax bracket and/or tax rates schedules may have an easier time using an editor to prepare subsequent runs from the first downloaded JSON reform file and then uploading the slightly edited JSON reform files via the TaxBrain file upload page.  Obviously the benefits will vary by user, but the cost of adding this to the output page would seem to be trivial because the file is already being generated.

I think adding the JSON reform file to the output page and suggesting use of the file upload capability is the obvious response to the user comment in #821.   The problem described in #821 is intrinsic to using a GUI input form.  So, the solution is to prepare TaxBrain input in a way that is more suitable to a project that involves specifying many policy reforms.  The cost of adding the suggested "rate schedule simplification" to either TaxBrain or Tax-Calculator is quite substantial.  In fact, after reviewing the existing Tax-Calculator logic, and the lack of testing of that logic, connected to the three parameters in the "Tax All Capital Gains And Dividends The Same As Regular Taxable Income" subsection of the "Capital Gains and Dividends" section of the GUI, I'm inclined to remove those parameter from Tax-Calculator.

**Comment by hdoupe** [comment]
+1. I think this is a good idea. The transparency and convenience benefits of this proposal are pretty substantial.

This shouldn't be very difficult to implement either. All GUI input data is parsed into the JSON file format and this format is saved. Thus, we could show the file results for all runs since September or so. Also, the file contents are already displayed for runs submitted through the file interface.

**Comment by martinholmer** [comment]
@hdoupe said in enhancement request #859:
> +1. I think this is a good idea. The transparency and convenience benefits of this proposal are pretty substantial.
>
> This shouldn't be very difficult to implement either. All GUI input data is parsed into the JSON file format and this format is saved. Thus, we could show the file results for all runs since September or so. Also, the file contents are already displayed for runs submitted through the file interface.

I'm glad you see the benefits and cost the same way as I do.
I'm looking forward to this TaxBrain enhancement!

**Comment by hdoupe** [comment]
@lucassz would you mind taking a look at this issue?

The relevant parts of the code are:

where the data is created:
https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/webapp/apps/taxbrain/param_formatters.py#L352-L368
```
    policy_dict_json = {"policy": policy_dict_json}

    policy_dict_json = json.dumps(policy_dict_json)

    assumptions_dict_json = {"behavior": assumptions_dict_json,
                             "growdiff_response": {},
                             "consumption": {},
                             "growdiff_baseline": {},
                             "growmodel": {}}
    assumptions_dict_json = json.dumps(assumptions_dict_json)

    (reform_dict, assumptions_dict,
        errors_warnings) = read_json_reform(policy_dict_json,
                                            assumptions_dict_json,
                                            use_puf_not_cps=use_puf_not_cps)

    # return (reform_dict, assumptions_dict, "", "", errors_warnings)
     # should be:
     return(reform_dict, assumptions_dict, policy_dict_json, assumptions_dict_json, errors_warnings)
```

and where the data is saved:
https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/webapp/apps/taxbrain/views.py#L245-L252
```
        json_reform = JSONReformTaxCalculator(
            reform_text=json.dumps(reform_dict),
            assumption_text=json.dumps(assumptions_dict),
            raw_reform_text=reform_text,
            raw_assumption_text=assumptions_text,
            errors_warnings_text=json.dumps(errors_warnings)
        )
        json_reform.save()
```

and where the data is sent to the frontend: 

https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/webapp/apps/taxbrain/views.py#L692-L700
```
    if (model.json_text is not None and (model.json_text.raw_reform_text or
       model.json_text.raw_assumption_text)):
        reform_file_contents = model.json_text.raw_reform_text
        reform_file_contents = reform_file_contents.replace(" ","&nbsp;")
        assump_file_contents = model.json_text.raw_assumption_text
        assump_file_contents = assump_file_contents.replace(" ","&nbsp;")
    else:
        reform_file_contents = False
        assump_file_contents = False
```

The `raw_reform_text` and `raw_assumption_text` are what you want to display. But, for GUI inputs, those are not saved (they should have been saved). One way to solve this is to return the JSON strings instead of the empty strings in `get_reform_from_gui`. That data would then be saved and will be rendered in the output page.

There are some backwards compatibility issues since the data was not saved in previous runs. We can talk through how to solve these issues when you open a PR with the first step done.

**Comment by hdoupe** [comment]
@martinholmer #859 should be resolved. An example for this can be found here: https://ospc-test.herokuapp.com/taxbrain/53/ 

Do you have any feedback? 

This feature isn't working on the dynamic results page. I'm working to resolve this now.

**Comment by martinholmer** [comment]
@hdoupe said:
> #859 should be resolved. An example for this can be found here:
> https://ospc-test.herokuapp.com/taxbrain/53/

Do you have any feedback?

Looks fine, as long as users can copy and paste the reform and assumptions text.

**Comment by hdoupe** [comment]
Yep, they can. Thanks for checking @martinholmer.
