### ISSUE TITLE
Benefit Repeal Switch Issues

### ISSUE THREAD

**Issue by andersonfrailey** [OpenSourcePolicyCenter/PolicyBrain#866]
I noticed while running the test app that to repeal benefit programs you must enter "1" rather than there being some type of switch or button to indicate benefit repeal as the name implies. This could be cause problems if a user enters a value that isn't zero or one because tax-calculator is expecting a true/false input. Is it possible to change this?
<img width="785" alt="screen shot 2018-03-26 at 11 17 32 am" src="https://user-images.githubusercontent.com/20684675/37915429-80feb064-30e7-11e8-8099-f7fe2a75fbfe.png">

**Comment by hdoupe** [comment]
@andersonfrailey Thanks for the suggestion. Yes, PolicyBrain can change this. Instead of adding a button, would it be OK if we displayed the default option as 'False'? I think this sufficiently emphasizes that this is a switch. Further, if we go with the text box and displaying 'True'/'False', then the user can use the reverse and wildcard operators to repeal these programs in the year prior to the start year or in later years.
